### PR TITLE
allow changes to config, not config-sample

### PR DESCRIPTION
**Pull request by bri-bri**
Hi. This caused a bit of pain. I think it makes more sense to gitignore `config-sample.json` and allow changes to `config.json`?

### CODE REVIEW

**Comment by nateklaiber** [comment]
@bri-bri - `config.json` contains sensitive information that you don't want stored in version control. When you clone the repository, you will want to `cp config-sample.json config.json` and fill in the values with your Automatic client information and other variables that need to be kept private. The sample is provided as a convenience so you know what values to fill in.

**Comment by bri-bri** [comment]
Yeah, I was up too late and delirious. Silly!

**Comment by nateklaiber** [comment]
No worries, here's some :coffee: for the next late night! :smiley:

**Comment by bri-bri** [comment]
Thanks :smiley:  I'll set some aside for the next confused soul who tries to deploy to heroku without checking the .gitignore first.

**Pull request closed without merging**
